apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service2
  namespace: default
spec:
  selector:
    app: myapp2
  ports:
    - port: 80
      targetPort: 80
