apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo-https
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: podinfo-https
  releaseName: podinfo-https
  values:
    replicaCount: 3
